<?php
//2016/10/09 - 11:34:04
use Illuminate\Database\Seeder;

/** @noinspection PhpUndefinedClassInspection */
class SubjectSeeder extends Seeder
{

    public function run()
    {

        App\Subject::create(json_decode('{"ais_id":"313697","study_level":2,"en":{"code":"I-URY","name":"Accelerators"},"sk":{"code":"I-URY","name":"Ur\u00fdch\u013eova\u010de"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313708","study_level":2,"en":{"code":"I-ADRIA","name":"Adaptive Control"},"sk":{"code":"I-ADRIA","name":"Adapt\u00edvne riadenie"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313590","study_level":2,"en":{"code":"I-PMRMS","name":"Advanced control methods for mechatronic systems"},"sk":{"code":"I-PMRMS","name":"Pokro\u010dil\u00e9 met\u00f3dy riadenia mechatronick\u00fdch syst\u00e9mov"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313714","study_level":2,"en":{"code":"I-PTAR","name":"Advanced Control Theory"},"sk":{"code":"I-PTAR","name":"Pokro\u010dil\u00e1 TAR"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313741","study_level":2,"en":{"code":"I-PMSOV","name":"Advanced Methods of Image and Video Processing"},"sk":{"code":"I-PMSOV","name":"Pokro\u010dil\u00e9 met\u00f3dy spracovania obrazu a videa"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313173","study_level":1,"en":{"code":"B-AZA","name":"Analysis and complexity of algorithms"},"sk":{"code":"B-AZA","name":"Anal\u00fdza a zlo\u017eitos\u0165 algoritmov"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313530","study_level":2,"en":{"code":"I-ASEO2","name":"Analysis and Synthesis of Electric Circuits 2"},"sk":{"code":"I-ASEO2","name":"Anal\u00fdza a synt\u00e9za elektrick\u00fdch obvodov 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313731","study_level":2,"en":{"code":"I-AST","name":"Aplications of smart terminals"},"sk":{"code":"I-AST","name":"Aplik\u00e1cie smart termin\u00e1lov"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313531","study_level":2,"en":{"code":"I-AMAG","name":"Applied Magnetism"},"sk":{"code":"I-AMAG","name":"Aplikovan\u00fd magnetizmus"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313456","study_level":1,"en":{"code":"B-APMAT","name":"Applied Mathematics"},"sk":{"code":"B-APMAT","name":"Aplikovan\u00e1 matematika"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313682","study_level":2,"en":{"code":"I-AOPT","name":"Applied optics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"314186","study_level":1,"en":{"code":"B-APROG","name":"Applied programming"}}', true));
        App\Subject::create(json_decode('{"ais_id":"317959","study_level":1,"en":{"code":"B-UMINT","name":"Artificial Intelligence"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313718","study_level":2,"en":{"code":"I-UMINT2","name":"Artificial Intelligence 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313462","study_level":1,"en":{"code":"B-TPR","name":"Automatic Control Hardware"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313578","study_level":2,"en":{"code":"I-ASRAV","name":"Automatic control systems in car production"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313244","study_level":1,"en":{"code":"B-SAR2","name":"Automatic Control Systems 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313457","study_level":1,"en":{"code":"B-AR1","name":"Automatic Control 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313592","study_level":2,"en":{"code":"I-TSAE","name":"Automotive and electromobile transmission systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313267","study_level":1,"en":{"code":"B-ELSA","name":"Automotive Electronic Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313588","study_level":2,"en":{"code":"I-OSA","name":"Automotive Lighting Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313458","study_level":1,"en":{"code":"B-BP1-RK","name":"Bachelor project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313175","study_level":1,"en":{"code":"B-BP1-AI","name":"Bachelor project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313465","study_level":1,"en":{"code":"B-BP1-TL","name":"Bachelor Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313230","study_level":1,"en":{"code":"B-BP1-AME","name":"Bachelor Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313308","study_level":1,"en":{"code":"B-BP1-EE","name":"Bachelor Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313329","study_level":1,"en":{"code":"B-BP1-EN","name":"Bachelor Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"314187","study_level":1,"en":{"code":"B-BP1-ET","name":"Bachelor Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313430","study_level":1,"en":{"code":"B-BP1-JFI","name":"Bachelor Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319868","study_level":1,"en":{"code":"B-BP2-TL","name":"Bachelor Project 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"318787","study_level":1,"en":{"code":"B-BZP-RK","name":"Bachelor Thesis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"318785","study_level":1,"en":{"code":"B-BZP-EE","name":"Bachelor Thesis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"318786","study_level":1,"en":{"code":"B-BZP-JFI","name":"Bachelor Thesis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313314","study_level":1,"en":{"code":"B-MODEE","name":"Basics in Modelling in Power Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313201","study_level":1,"en":{"code":"B-ZMP","name":"Basics of Management and Enterprize"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313709","study_level":2,"en":{"code":"I-BKYB","name":"Biocybernetics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313683","study_level":2,"en":{"code":"I-BEN","name":"Bioelectronics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313579","study_level":2,"en":{"code":"I-BMS","name":"Biomechatronic systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313633","study_level":2,"en":{"code":"I-BFYZ","name":"Biophysics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313580","study_level":2,"en":{"code":"I-CSPMS","name":"CAD and mechatronics systems design"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313634","study_level":2,"en":{"code":"I-CAEEP","name":"CAE of Electronic Devices"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313581","study_level":2,"en":{"code":"I-CAEMS","name":"CAE of Mechatronic Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313182","study_level":1,"en":{"code":"B-KSIF","name":"Classical ciphers"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313333","study_level":1,"en":{"code":"B-KIS","name":"Communication and Information Networks"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313185","study_level":1,"en":{"code":"B-MAKO","name":"Communication management"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313642","study_level":2,"en":{"code":"I-PAO","name":"Computer Circuit Analysis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313190","study_level":1,"en":{"code":"B-PS","name":"Computer networks"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313435","study_level":1,"en":{"code":"B-PORFI","name":"Computer Networks and Controls in Nuclear and Physical Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313539","study_level":2,"en":{"code":"I-PVID","name":"Computer Vision"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313716","study_level":2,"en":{"code":"I-RRM","name":"Control of Industrial Robots"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313715","study_level":2,"en":{"code":"I-RMS","name":"Control of Mechatronic Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319870","study_level":2,"en":{"code":"I-RMR","name":"Control of Mobile Robots"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313620","study_level":2,"en":{"code":"I-RES","name":"Control of Power Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313461","study_level":1,"en":{"code":"B-RS","name":"Control Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313564","study_level":2,"en":{"code":"I-ZKRY","name":"Cryptography"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313698","study_level":2,"en":{"code":"I-VJE","name":"Deccommissioning of Nuclear Power Plants"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313558","study_level":2,"en":{"code":"I-NKS","name":"Design and cryptanalysis of ciphers"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313243","study_level":1,"en":{"code":"B-SAEMOB","name":"Design of Automobiles and Electromobiles"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313537","study_level":2,"en":{"code":"I-NMS","name":"Design of Measuring Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313269","study_level":1,"en":{"code":"B-TINA","name":"Design of Web Applications"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313742","study_level":2,"en":{"code":"I-PBTS","name":"Designing of Wireless Telecommunication Networks"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313593","study_level":2,"en":{"code":"I-VPPMS","name":"Development programming environment for mechatronic systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313330","study_level":1,"en":{"code":"B-CIMO","name":"Digital and Impulse Circuits"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313466","study_level":1,"en":{"code":"B-DK2","name":"Digital Communications 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313734","study_level":2,"en":{"code":"I-CSO","name":"Digital Image Processing"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313532","study_level":2,"en":{"code":"I-CSSE","name":"Digital signal Processing"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313736","study_level":2,"en":{"code":"I-CSST","name":"Digital Signal Processing"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313635","study_level":2,"en":{"code":"I-CISPSI","name":"Digital Signal Processing"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313735","study_level":2,"en":{"code":"I-CSR","name":"Digital Speech Processing"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313554","study_level":2,"en":{"code":"I-DP1-AI","name":"Diploma project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313737","study_level":2,"en":{"code":"I-DP1-TL","name":"Diploma Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313609","study_level":2,"en":{"code":"I-DP2-ENE","name":"Diploma Project 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313533","study_level":2,"en":{"code":"I-DP2-AE","name":"Diploma Project 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313636","study_level":2,"en":{"code":"I-DP2-EN","name":"Diploma Project 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319272","study_level":1,"en":{"code":"B-DUSRK","name":"Discrete Event Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313177","study_level":1,"en":{"code":"B-DUS","name":"Discrete Event Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313534","study_level":2,"en":{"code":"I-DMS","name":"Distributed Measurement Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313610","study_level":2,"en":{"code":"I-DSPROJ","name":"Distribution Networks and Planning"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313685","study_level":2,"en":{"code":"I-DOZ","name":"Dosimetry"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313619","study_level":2,"en":{"code":"I-PVE","name":"Drives and Power Electronics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313178","study_level":1,"en":{"code":"B-EKENS","name":"Economics of Power Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313536","study_level":2,"en":{"code":"I-MEENZ","name":"Electrical Energy Converters and Power Supplies"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319230","study_level":1,"en":{"code":"B-ELRAK","name":"Electrical Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313179","study_level":1,"en":{"code":"B-ELINFO","name":"Electrical Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313231","study_level":1,"en":{"code":"B-ELT1","name":"Electrical Engineering 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313332","study_level":1,"en":{"code":"B-ELT2I","name":"Electrical Engineering 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313310","study_level":1,"en":{"code":"B-ELSTR","name":"Electrical Machines"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313611","study_level":2,"en":{"code":"I-ESP","name":"Electrical Substations and Equipments"}}', true));
        App\Subject::create(json_decode('{"ais_id":"314188","study_level":1,"en":{"code":"B-EMC","name":"Electromagnetic Compatibility"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313535","study_level":2,"en":{"code":"I-EPS","name":"Electromagnetic Devices and Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313331","study_level":1,"en":{"code":"B-EPON","name":"Electronic Devices and Circuits"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313686","study_level":2,"en":{"code":"I-ESTL","name":"Electronic Strukture of Matter"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313232","study_level":1,"en":{"code":"B-ELT2E","name":"Electrotechnology 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313719","study_level":2,"en":{"code":"I-VRS","name":"Embedded control systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313681","study_level":2,"en":{"code":"I-VMSM","name":"Embedded microcontrollers systems in mechatronics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313233","study_level":1,"en":{"code":"B-ENEF","name":"Energy Efficiency"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313614","study_level":2,"en":{"code":"I-IEKO","name":"Engineering Ecology"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313713","study_level":2,"en":{"code":"I-OP","name":"Engineering Practice"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313174","study_level":1,"en":{"code":"B-AJ1","name":"English Language 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313687","study_level":2,"en":{"code":"I-ERF","name":"Experimental Reactor Physics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313459","study_level":1,"en":{"code":"B-FSS","name":"Filtering and signal processing"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313584","study_level":2,"en":{"code":"I-MKP","name":"Finite element method"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313488","study_level":2,"en":{"code":"I-NJ","name":"German Language"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313169","study_level":1,"en":{"code":"B-NJ","name":"German Language"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313313","study_level":1,"en":{"code":"B-TVN","name":"High Voltage Technology"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313460","study_level":1,"en":{"code":"B-ISZ","name":"Information Systems in Health Care"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313613","study_level":2,"en":{"code":"I-IEIB","name":"Intelligent Electrical Installations in Buildings"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313338","study_level":1,"en":{"code":"B-UIT","name":"Introduction into Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313245","study_level":1,"en":{"code":"B-UIE","name":"Introduction into Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313199","study_level":1,"en":{"code":"B-UII","name":"Introduction into Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"314191","study_level":1,"en":{"code":"B-ZAUT","name":"Introduction to Automatization"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313563","study_level":2,"en":{"code":"I-UPB","name":"Introduction to computer security"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313467","study_level":1,"en":{"code":"B-IPV6","name":"IPv6 and Internet of Things"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313560","study_level":2,"en":{"code":"I-RZZ","name":"Knowledge representation"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313559","study_level":2,"en":{"code":"I-OPTP1","name":"Laboratory skills and Team Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313621","study_level":2,"en":{"code":"I-STA","name":"Lighting Applications"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313618","study_level":2,"en":{"code":"I-OZS","name":"Lighting Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313312","study_level":1,"en":{"code":"B-SVET","name":"Lighting Technology"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313183","study_level":1,"en":{"code":"B-LA","name":"Linear Algebra"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319167","study_level":1,"en":{"code":"PSTSK","name":"Logging on state examination"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313555","study_level":2,"en":{"code":"I-LOG","name":"Logic"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313236","study_level":1,"en":{"code":"B-LSE","name":"Logic Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313184","study_level":1,"en":{"code":"B-LSI","name":"Logical systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313562","study_level":2,"en":{"code":"I-SUNS","name":"Machine learning and Neural networks"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313684","study_level":2,"en":{"code":"I-DP2-JFI","name":"Master Project 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319479","study_level":2,"en":{"code":"I-DZP-TL","name":"Master Thesis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319476","study_level":2,"en":{"code":"I-DZP-AME","name":"Master Thesis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319477","study_level":2,"en":{"code":"I-DZP-JFI","name":"Master Thesis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319478","study_level":2,"en":{"code":"I-DZP-RK","name":"Master Thesis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313710","study_level":2,"en":{"code":"I-DP2-RK","name":"Master\u0027s thesis project 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313582","study_level":2,"en":{"code":"I-DP2-AME","name":"Master\u0027s thesis project 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313691","study_level":2,"en":{"code":"I-MST","name":"Materials Structures and Technologies"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313690","study_level":2,"en":{"code":"I-MAT","name":"Mathematics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313186","study_level":1,"en":{"code":"B-MAT1I","name":"Mathematics 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313237","study_level":1,"en":{"code":"B-MAT1E","name":"Mathematics 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313187","study_level":1,"en":{"code":"B-MAT2I","name":"Mathematics 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313238","study_level":1,"en":{"code":"B-MAT2E","name":"Mathematics 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313239","study_level":1,"en":{"code":"B-MAT3","name":"Mathematics 3"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313432","study_level":1,"en":{"code":"B-MAT4","name":"Mathematics 4"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313241","study_level":1,"en":{"code":"B-MER1","name":"Measurement Technology 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"314189","study_level":1,"en":{"code":"B-MER2","name":"Measurement Technology 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313692","study_level":2,"en":{"code":"I-MRJE","name":"Measuremet and Control of Nuclear Power Plants"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313240","study_level":1,"en":{"code":"B-MECH","name":"Mechanics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319433","study_level":2,"en":{"code":"I-MEMSISA","name":"MEMS -- intelligent sensors and actuators"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313468","study_level":1,"en":{"code":"B-MOPM","name":"Metallic and Optical Transmission Media"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313615","study_level":2,"en":{"code":"I-MOVK","name":"Metallic and Optical Wires and Cables"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313638","study_level":2,"en":{"code":"I-MAMS","name":"Methods of material and structure analysis"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313433","study_level":1,"en":{"code":"B-MEDIM","name":"Methods of Material Diagnostics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313334","study_level":1,"en":{"code":"B-ME","name":"Microelectronics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"314190","study_level":1,"en":{"code":"B-MIP1","name":"Microprocessor Engineering 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313552","study_level":2,"en":{"code":"I-MIP2","name":"Microprocessor Engineering 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313188","study_level":1,"en":{"code":"B-MPP","name":"Microprocessors and their Programming"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313556","study_level":2,"en":{"code":"I-MOBV","name":"Mobile Computing"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313557","study_level":2,"en":{"code":"I-MSUS","name":"Modeling and simulation of event systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313242","study_level":1,"en":{"code":"B-MSLAB","name":"Modeling and Simulation Using Matlab"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313585","study_level":2,"en":{"code":"I-MRNMS","name":"Modelling and control of nonlinear mechatronic systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313434","study_level":1,"en":{"code":"B-MODSIMF","name":"Modelling and Simulations"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313586","study_level":2,"en":{"code":"I-MTMP","name":"Multimedia and Telematics for Mobile Platforms"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313639","study_level":2,"en":{"code":"I-MMEDT","name":"Multimedia Technology"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313469","study_level":1,"en":{"code":"B-MTSS","name":"Multimedia Telecommunication Networks and Services"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313508","study_level":1,"en":{"code":"B-MM1","name":"Multimedia 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313640","study_level":2,"en":{"code":"I-NSE","name":"Nanoelectronics and Superconductor Electronics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313693","study_level":2,"en":{"code":"I-NANT","name":"Nanotechnology"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313717","study_level":2,"en":{"code":"I-SSR","name":"Network Control Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313587","study_level":2,"en":{"code":"I-NPAE","name":"Nonconventional automotive and electromobile drives"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313431","study_level":1,"en":{"code":"B-JFT","name":"Nuclear Physics and Technology"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313689","study_level":2,"en":{"code":"I-JEND","name":"Nuclear Electronics and Detectors"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313696","study_level":2,"en":{"code":"I-SZJE","name":"Nuclear Power Facilities"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313538","study_level":2,"en":{"code":"I-NM","name":"Numerical Methods"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313617","study_level":2,"en":{"code":"I-OES","name":"Off-grid power systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313189","study_level":1,"en":{"code":"B-OS","name":"Operating systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313694","study_level":2,"en":{"code":"I-PJE","name":"Operation of Nuclear Power Plants"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313641","study_level":2,"en":{"code":"I-OKS-EN","name":"Optical Communication Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313608","study_level":2,"en":{"code":"I-OPM","name":"Optimization in mechatronics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313740","study_level":2,"en":{"code":"I-OKS","name":"Optocommunications Systems and Networks"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313335","study_level":1,"en":{"code":"B-OPTEL","name":"Optoelectronics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319934","study_level":2,"en":{"code":"I-PPDS","name":"Paralel programming and distributed systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313612","study_level":2,"en":{"code":"I-FKMET","name":"Photometry and Colorimetry"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313688","study_level":2,"en":{"code":"I-FMM","name":"Photonic Materials and Metamaterials"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313637","study_level":2,"en":{"code":"I-FTN","name":"Photonics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313196","study_level":1,"en":{"code":"B-TVOS1","name":"Physical Education for People with Health Problems 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"318092","study_level":1,"en":{"code":"B-TVOS2","name":"Physical Education for People with Health Problems 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313197","study_level":1,"en":{"code":"B-TVOS3","name":"Physical Education for People with Health Problems 3"}}', true));
        App\Subject::create(json_decode('{"ais_id":"318093","study_level":1,"en":{"code":"B-TVOS4","name":"Physical Education for People with Health Problems 4"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313198","study_level":1,"en":{"code":"B-TVOS5","name":"Physical Education for People with Health Problems 5"}}', true));
        App\Subject::create(json_decode('{"ais_id":"318094","study_level":1,"en":{"code":"B-TVOS6","name":"Physical Education for People with Health Problems 6"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319649","study_level":2,"en":{"code":"I-TK","name":"Physical Exercises"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319890","study_level":1,"en":{"code":"B-TK","name":"Physical Exercises"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313193","study_level":1,"en":{"code":"B-TK1","name":"Physical Exercises 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"317956","study_level":1,"en":{"code":"B-TK2","name":"Physical Exercises 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313194","study_level":1,"en":{"code":"B-TK3","name":"Physical Exercises 3"}}', true));
        App\Subject::create(json_decode('{"ais_id":"318091","study_level":1,"en":{"code":"B-TK4","name":"Physical Exercises 4"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313195","study_level":1,"en":{"code":"B-TK5","name":"Physical Exercises 5"}}', true));
        App\Subject::create(json_decode('{"ais_id":"317953","study_level":1,"en":{"code":"B-TK6","name":"Physical Exercises 6"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313180","study_level":1,"en":{"code":"B-FYZ1","name":"Physics 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313181","study_level":1,"en":{"code":"B-FYZ2I","name":"Physics 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313234","study_level":1,"en":{"code":"B-FYZ2E","name":"Physics 2"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313235","study_level":1,"en":{"code":"B-FYZ3","name":"Physics 3"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313268","study_level":1,"en":{"code":"B-PLCM","name":"PLC Systems in Mechatronics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313589","study_level":2,"en":{"code":"I-PHSMA","name":"Pneumatic and Hydraulic Systems in Mechatronic Applications"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313309","study_level":1,"en":{"code":"B-ELEK1","name":"Power Stations 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313463","study_level":1,"en":{"code":"B-VS","name":"Production Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313191","study_level":1,"en":{"code":"B-PT","name":"Programing techniques"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313695","study_level":2,"en":{"code":"I-PROJ-JFI","name":"Project"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313540","study_level":2,"en":{"code":"I-PROJ-AE","name":"Project"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313591","study_level":2,"en":{"code":"I-PROJ-AME","name":"Project"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313712","study_level":2,"en":{"code":"I-MPROJ","name":"Project Management"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313336","study_level":1,"en":{"code":"B-PRP","name":"Project Planning and Management"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313616","study_level":2,"en":{"code":"I-OAES","name":"Protections and Automatics in Power Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313739","study_level":2,"en":{"code":"I-NTSS","name":"Public Telecommunication Systems, Networks and Services"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313489","study_level":2,"en":{"code":"I-RJ","name":"Russian Language"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313170","study_level":1,"en":{"code":"B-RJ","name":"Russian Language"}}', true));
        App\Subject::create(json_decode('{"ais_id":"317448","study_level":2,"en":{"code":"I-BEZ","name":"Safety in Electrical Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313176","study_level":1,"en":{"code":"B-BEZ","name":"Safety in Electrical Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313733","study_level":2,"en":{"code":"I-BTSS","name":"Security of Communication Networks and Services"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313644","study_level":2,"en":{"code":"I-SMIK","name":"Sensor Microsystems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313337","study_level":1,"en":{"code":"B-SENZ","name":"Sensorics"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313583","study_level":2,"en":{"code":"I-INSEMOB","name":"Smart grid in e-mobility"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313541","study_level":2,"en":{"code":"I-SPAE","name":"Social and Legal Aspects in Electrical Engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313561","study_level":2,"en":{"code":"I-SMPSVIS","name":"Social, ethical and legal aspects of information systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313553","study_level":2,"en":{"code":"I-ASOS","name":"Software architecture"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313192","study_level":1,"en":{"code":"B-SWI","name":"Software engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313311","study_level":1,"en":{"code":"B-SEPS","name":"Solar energy devices and systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319480","study_level":2,"en":{"code":"I-SSP-TL","name":"State Exam"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319481","study_level":2,"en":{"code":"I-SSP-AME","name":"State exam from the subject"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319482","study_level":2,"en":{"code":"I-SSP-JFI","name":"State Examination"}}', true));
        App\Subject::create(json_decode('{"ais_id":"319483","study_level":2,"en":{"code":"I-SSP-RK","name":"State examination from the subject"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313622","study_level":2,"en":{"code":"I-USES","name":"Steady-State Power Systems"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313711","study_level":2,"en":{"code":"I-IDS","name":"Systems Identification"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313646","study_level":2,"en":{"code":"I-TP-EN","name":"Team Project"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313744","study_level":2,"en":{"code":"I-TP1-TL","name":"Team Project 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313743","study_level":2,"en":{"code":"I-RTS","name":"Telecommunication Networks Management"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313645","study_level":2,"en":{"code":"I-TMEDT","name":"Telemedicine engineering"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313738","study_level":2,"en":{"code":"I-KPV","name":"Video Coding and Transmission"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313270","study_level":1,"en":{"code":"B-VIPROT","name":"Virtual Prototyping"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313200","study_level":1,"en":{"code":"B-WEBTE1","name":"Web technologies 1"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313643","study_level":2,"en":{"code":"I-RST","name":"Wireless Communication Systems and Routes"}}', true));
        App\Subject::create(json_decode('{"ais_id":"313732","study_level":2,"en":{"code":"I-BEK","name":"Wireless Communications"}}', true));

    }
}
